#!/usr/bin/env bash
# shellcheck disable=SC1091
#
# Installs system-level dependencies (auditd, python3/venv) via whichever
# package manager is present, then builds an ISOLATED python venv and
# installs the auditsys package into it — system/global python site-packages
# are never touched (no --break-system-packages, no --user pollution).
#
# Thin wrapper scripts (audit-cli / audit-tui) are placed on PATH that just
# exec the venv's binaries, so the command-line UX is unchanged.
#
# Rule installation (bin/install-audit-rules.sh) is a separate opt-in step —
# this script only gets you to "the tools exist and audit-cli runs."
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_TIMER=0
SKIP_SYSTEM_DEPS=0
VENV_DIR=""
BIN_DIR=""

usage() {
    cat <<EOF
Usage: $0 [--with-timer] [--skip-system-deps] [--venv-dir PATH] [--bin-dir PATH]

  --with-timer         also install the systemd timer for periodic 'audit-cli sync'
  --skip-system-deps   skip apt/dnf/pacman/zypper package installation (assume already present)
  --venv-dir PATH      where to build the isolated venv
                        (default: /opt/auditsys/venv if root, else ~/.local/share/auditsys/venv)
  --bin-dir PATH       where to place audit-cli/audit-tui wrapper scripts
                        (default: /usr/local/bin if root, else ~/.local/bin)

Nothing here ever installs into system/global python site-packages: the
auditsys package only ever lives inside the venv this script creates.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --with-timer) INSTALL_TIMER=1; shift ;;
        --skip-system-deps) SKIP_SYSTEM_DEPS=1; shift ;;
        --venv-dir) VENV_DIR="$2"; shift 2 ;;
        --bin-dir) BIN_DIR="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown arg: $1" >&2; usage; exit 1 ;;
    esac
done

log() { echo "[install] $*"; }

is_root() { [[ "$(id -u)" -eq 0 ]]; }

if [[ -z "$VENV_DIR" ]]; then
    if is_root; then VENV_DIR="/opt/auditsys/venv"
    else VENV_DIR="$HOME/.local/share/auditsys/venv"
    fi
fi
if [[ -z "$BIN_DIR" ]]; then
    if is_root; then BIN_DIR="/usr/local/bin"
    else BIN_DIR="$HOME/.local/bin"
    fi
fi

detect_pkg_manager() {
    if command -v apt-get >/dev/null 2>&1; then echo apt
    elif command -v dnf >/dev/null 2>&1; then echo dnf
    elif command -v yum >/dev/null 2>&1; then echo yum
    elif command -v pacman >/dev/null 2>&1; then echo pacman
    elif command -v zypper >/dev/null 2>&1; then echo zypper
    else echo unknown
    fi
}

# Only system-level tools go through the package manager: python3 itself,
# the stdlib venv module, and auditd. The auditsys package never does.
install_system_deps() {
    local mgr="$1"
    log "detected package manager: $mgr"
    case "$mgr" in
        apt)
            sudo apt-get update -y
            sudo apt-get install -y python3 python3-venv auditd audit
            ;;
        dnf)
            sudo dnf install -y python3 audit
            ;;
        yum)
            sudo yum install -y python3 audit
            ;;
        pacman)
            sudo pacman -Sy --noconfirm python audit
            ;;
        zypper)
            sudo zypper install -y python3 python3-venv audit
            ;;
        *)
            log "unrecognized package manager — install python3 (with venv) and auditd manually, then re-run with --skip-system-deps"
            exit 1
            ;;
    esac
}

mgr="$(detect_pkg_manager)"
if [[ "$SKIP_SYSTEM_DEPS" -eq 0 ]]; then
    install_system_deps "$mgr"
else
    log "skipping system dependency installation (--skip-system-deps)"
fi

log "creating isolated venv at $VENV_DIR (system python untouched)"
python3 -m venv "$VENV_DIR"

log "installing auditsys into the venv only"
"$VENV_DIR/bin/pip" install --upgrade pip --quiet
"$VENV_DIR/bin/pip" install "$SCRIPT_DIR"

mkdir -p "$BIN_DIR"
for cmd in audit-cli audit-tui; do
    wrapper="$BIN_DIR/$cmd"
    cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# Thin wrapper — the real install lives in an isolated venv, never touching
# system python packages. Regenerated by scripts/install.sh.
exec "$VENV_DIR/bin/$cmd" "\$@"
EOF
    chmod +x "$wrapper"
    log "installed wrapper: $wrapper -> $VENV_DIR/bin/$cmd"
done

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) log "note: $BIN_DIR is not on your PATH — add 'export PATH=\"$BIN_DIR:\$PATH\"' to your shell rc" ;;
esac

log "ensuring default config exists"
"$VENV_DIR/bin/audit-cli" config init || true

if [[ "$INSTALL_TIMER" -eq 1 ]]; then
    if ! is_root; then
        log "note: --with-timer normally requires root to install a system-wide systemd unit"
    fi
    log "installing systemd timer for periodic sync"
    sudo tee /etc/systemd/system/audit-system-sync.service > /dev/null <<EOF
[Unit]
Description=auditsys: sync audit events from auditd/journalctl/docker into local store
After=network.target auditd.service

[Service]
Type=oneshot
ExecStart=$VENV_DIR/bin/audit-cli sync
User=root
Nice=10
EOF
    sudo cp "$SCRIPT_DIR/systemd/audit-system-sync.timer" /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable --now audit-system-sync.timer
    log "timer enabled: systemctl status audit-system-sync.timer"
    log "(service ExecStart points at $VENV_DIR/bin/audit-cli, not the wrapper — systemd units don't use your shell PATH)"
fi

cat <<EOF

Done. auditsys is installed in an isolated venv at:
  $VENV_DIR
Your system/global python packages were not modified.

Next steps:
  1. (root, once) sudo $SCRIPT_DIR/bin/install-audit-rules.sh
       — installs the auditd rules that make docker/file attribution work
  2. audit-cli sync
  3. audit-cli blame /path/to/thing
  4. audit-tui        (interactive browser)
  5. audit-cli report --format html
EOF
